### ISSUE TITLE
DataType not found

### ISSUE THREAD

**Issue by ghost** [pquiring/QSharp#1]
In classlib compilation doing dotnet build with VS2017 64 bits (build tools):

Qt\Controls\ab\ABPacket.cs(102,32): error CS0246  ...     DataType not found   .....

Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core

**Comment by pquiring** [comment]
Do you use a release version?
If not try a recent checkout.  There are sometimes errors that get checked in.

**Comment by pquiring** [comment]
Added missing file, should work now.
